aureuserp/aureuserp

- plugins/webkul/accounts/src/Filament/Resources/BillResource.php
- plugins/webkul/accounts/src/Filament/Resources/CreditNoteResource.php
- plugins/webkul/accounts/src/Filament/Resources/InvoiceResource.php
- plugins/webkul/accounts/src/Filament/Resources/InvoiceResource/Actions/CancelAction.php
- plugins/webkul/accounts/src/Filament/Resources/RefundResource.php
- plugins/webkul/purchases/src/Filament/Clusters/Orders/Resources/OrderResource.php
- plugins/webkul/purchases/src/Filament/Clusters/Orders/Resources/OrderResource/Actions/CreateBillAction.php
- plugins/webkul/support/database/seeders/CompanySeeder.php
… applicable and refactor the company seeder
> Refactor state options in resource forms to exclude CANCEL state when applicable and refactor the company seeder

- plugins/webkul/recruitments/src/Filament/Clusters/Configurations/Resources/JobPositionResource.php
> Issue #47 has been fixed.

- plugins/webkul/security/src/Filament/Resources/UserResource/Pages/EditUser.php
> Issue #140 has been fixed.

- plugins/webkul/accounts/resources/lang/en/filament/resources/tax-group.php
- plugins/webkul/accounts/resources/lang/en/filament/resources/tax.php
Translation issue fix
closes:  #154
> Fix: issue  #154

- plugins/webkul/products/src/Filament/Resources/CategoryResource/Pages/ManageProducts.php
Ensured type, uom_id, and uom_po_id are correctly pre-filled using fillForm()
Closes #198
> Fix Default Values Not Populating in Filament Form (#198)

- plugins/webkul/security/src/Filament/Resources/TeamResource.php
Fixed Add Character Validation for Team Name to Prevent UI Issues
> Issue #134

- plugins/webkul/contacts/src/Filament/Resources/PartnerResource.php
- plugins/webkul/partners/resources/lang/en/filament/resources/partner.php
- plugins/webkul/partners/src/Filament/Resources/PartnerResource.php
Issue #186 fixed (Handled contraints exception of contact force delete)
> Issue #186 fixed (Handled contraints exception of contact force delete)

- plugins/webkul/accounts/src/Filament/Resources/PaymentTermResource.php
> Fix: Added validation rule for payment term early discount value #147

- plugins/webkul/sales/src/Filament/Clusters/Settings/Pages/ManageQuotationAndOrder.php
> Fix: #184 Added validation rule for Quotation Validity 

- plugins/webkul/products/src/Filament/Resources/ProductResource.php
> Issue #550 has been fixed.

- plugins/webkul/accounts/src/Filament/Resources/InvoiceResource.php
> Issue #540 has been fixed.

- plugins/webkul/website/resources/views/filament/customer/header/auth-links.blade.php
> issue #542 has been fixed.

- plugins/webkul/products/src/Filament/Resources/ProductResource.php
> Issue #539 has been fixed.

- plugins/webkul/support/src/Filament/Resources/ActivityTypeResource.php
- plugins/webkul/support/src/Filament/Resources/ActivityTypeResource/Pages/ListActivityTypes.php
- plugins/webkul/time-off/src/Filament/Clusters/Configurations/Resources/ActivityTypeResource.php
- plugins/webkul/time-off/src/Filament/Clusters/Configurations/Resources/ActivityTypeResource/Pages/CreateActivityType.php
- plugins/webkul/time-off/src/Filament/Clusters/Configurations/Resources/ActivityTypeResource/Pages/EditActivityType.php
- plugins/webkul/time-off/src/Filament/Clusters/Configurations/Resources/ActivityTypeResource/Pages/ListActivityTypes.php
> Issue #509 has been fixed.

- plugins/webkul/time-off/src/Enums/CarryoverDay.php
- plugins/webkul/time-off/src/Filament/Clusters/Configurations/Resources/AccrualPlanResource.php
- plugins/webkul/time-off/src/Filament/Clusters/Configurations/Resources/AccrualPlanResource/Pages/CreateAccrualPlan.php
- plugins/webkul/time-off/src/Filament/Clusters/Configurations/Resources/AccrualPlanResource/Pages/EditAccrualPlan.php
- plugins/webkul/time-off/src/Filament/Clusters/Configurations/Resources/AccrualPlanResource/Pages/ManageMilestone.php
- plugins/webkul/time-off/src/Filament/Clusters/Configurations/Resources/AccrualPlanResource/Pages/ViewAccrualPlan.php
- plugins/webkul/time-off/src/Models/LeaveAccrualPlan.php
> Issue #502 has been fixed.

- plugins/webkul/time-off/resources/lang/en/filament/widgets/calendar-widget.php
- plugins/webkul/time-off/src/Filament/Clusters/MyTime/Resources/MyAllocationResource.php
- plugins/webkul/time-off/src/Filament/Clusters/MyTime/Resources/MyTimeOffResource.php
- plugins/webkul/time-off/src/Filament/Pages/Dashboard.php
- plugins/webkul/time-off/src/Filament/Widgets/CalendarWidget.php
- plugins/webkul/time-off/src/TimeOffServiceProvider.php
Please uninstall the **Time Off** plugin and then reinstall it.
Reinstalling will ensure that all the necessary data is properly seeded for the plugin to work smoothly.
> This issue has been fixed. Kindly follow the steps above to verify the resolution.
> Issue #501 has been fixed.

- plugins/webkul/employees/src/Models/EmployeeJobPosition.php
> Issue #500 has been fixed.

- plugins/webkul/projects/src/Filament/Resources/ProjectResource.php
> Issue #491 has been fixed.

- plugins/webkul/sales/src/Filament/Clusters/Orders/Resources/QuotationResource.php
> Issue #480 has been fixed.

- plugins/webkul/inventories/src/Filament/Clusters/Operations/Resources/OperationResource.php
> Issue #473 has been fixed.

- plugins/webkul/projects/src/Models/Task.php
Clean Up Redundant deadline Cast Definition – Ref #467
> Clean Up Redundant deadline Cast Definition – Ref #467

- plugins/webkul/sales/src/Filament/Clusters/Orders/Resources/QuotationResource.php
> Issue #462 has been fixed.

- plugins/webkul/accounts/src/Filament/Resources/TaxResource.php
> Issue #457 has been fixed.

- plugins/webkul/purchases/resources/lang/en/filament/admin/clusters/orders/resources/quotation.php
- plugins/webkul/purchases/resources/lang/en/filament/admin/clusters/orders/resources/quotation/pages/list-quotation.php
- plugins/webkul/purchases/src/Filament/Admin/Clusters/Orders/Resources/QuotationResource/Pages/ListQuotations.php
> Issue #603 has been fixed.

- plugins/webkul/invoices/src/Filament/Clusters/Vendors/Resources/VendorResource/Pages/CreateVendor.php
- plugins/webkul/invoices/src/Filament/Clusters/Vendors/Resources/VendorResource/Pages/EditVendor.php
- plugins/webkul/invoices/src/Filament/Clusters/Vendors/Resources/VendorResource/Pages/ListVendors.php
- plugins/webkul/invoices/src/Filament/Clusters/Vendors/Resources/VendorResource/Pages/ManageAddresses.php
- plugins/webkul/invoices/src/Filament/Clusters/Vendors/Resources/VendorResource/Pages/ManageBankAccounts.php
- plugins/webkul/invoices/src/Filament/Clusters/Vendors/Resources/VendorResource/Pages/ManageContacts.php
- plugins/webkul/invoices/src/Filament/Clusters/Vendors/Resources/VendorResource/Pages/ViewVendor.php
> Issue #538 has been fixed.

- plugins/webkul/recruitments/resources/lang/en/filament/clusters/applications/resources/candidate.php
> Issue #618 has been fixed.

- plugins/webkul/invoices/src/Filament/Clusters/Customer/Resources/PartnerResource/Pages/ManageBankAccounts.php
- plugins/webkul/partners/src/Filament/Resources/BankAccountResource.php
- plugins/webkul/partners/src/Models/BankAccount.php
> Issue #546 has been fixed.

- plugins/webkul/projects/resources/lang/en/filament/clusters/configurations/resources/project-stage.php
- plugins/webkul/projects/src/Filament/Clusters/Configurations/Resources/ProjectStageResource.php
- plugins/webkul/projects/src/Models/ProjectStage.php
> Issue #495 has been fixed.

- plugins/webkul/accounts/resources/lang/en/filament/resources/invoice.php
- plugins/webkul/accounts/src/Filament/Resources/InvoiceResource.php
> Issue #634 has been fixed.

- plugins/webkul/sales/src/Filament/Clusters/Orders/Resources/QuotationResource/Pages/ManageDeliveries.php
> Issue #620 has been fixed.

- plugins/webkul/inventories/src/Filament/Clusters/Operations/Resources/OperationResource.php
- plugins/webkul/recruitments/src/Filament/Clusters/Applications/Resources/ApplicantResource/Pages/ListApplicants.php
- routes/web.php
> Issue #507 has been fixed.

- plugins/webkul/projects/resources/lang/en/filament/widgets/stats-overview.php
- plugins/webkul/projects/resources/lang/en/filament/widgets/task-by-stage.php
- plugins/webkul/projects/resources/lang/en/filament/widgets/task-by-state.php
- plugins/webkul/projects/resources/lang/en/filament/widgets/top-assignees.php
- plugins/webkul/projects/resources/lang/en/filament/widgets/top-projects.php
- plugins/webkul/projects/src/Filament/Widgets/StatsOverviewWidget.php
- plugins/webkul/projects/src/Filament/Widgets/TaskByStageChart.php
- plugins/webkul/projects/src/Filament/Widgets/TaskByStateChart.php
- plugins/webkul/projects/src/Filament/Widgets/TopAssigneesWidget.php
- plugins/webkul/projects/src/Filament/Widgets/TopProjectsWidget.php
- plugins/webkul/recruitments/resources/lang/en/filament/widgets/applicant.php
- plugins/webkul/recruitments/resources/lang/en/filament/widgets/job-position.php
- plugins/webkul/recruitments/src/Filament/Widgets/ApplicantChartWidget.php
- plugins/webkul/recruitments/src/Filament/Widgets/JobPositionStatsWidget.php
- plugins/webkul/time-off/resources/lang/en/filament/widgets/calendar-widget.php
- plugins/webkul/time-off/resources/lang/en/filament/widgets/my-time-off-widget.php
- plugins/webkul/time-off/resources/lang/en/filament/widgets/overview-calendar-widget.php
- plugins/webkul/time-off/src/Filament/Widgets/CalendarWidget.php
- plugins/webkul/time-off/src/Filament/Widgets/MyTimeOffWidget.php
- plugins/webkul/time-off/src/Filament/Widgets/OverviewCalendarWidget.php
> Issue #649 has been fixed.

- plugins/webkul/sales/src/Filament/Clusters/Orders/Resources/QuotationResource.php
add placeholder int term and conditions.
> add placeholder in term and conditions.

- plugins/webkul/sales/src/Filament/Clusters/Orders/Resources/QuotationResource.php
> Issue #665 has been fixed.

- plugins/webkul/inventories/src/Filament/Clusters/Configurations/Resources/RouteResource.php
> Issue #663 has been fixed.

- plugins/webkul/employees/resources/lang/en/filament/resources/department/pages/edit-department.php
- plugins/webkul/employees/src/Filament/Resources/DepartmentResource.php
- plugins/webkul/employees/src/Filament/Resources/DepartmentResource/Pages/EditDepartment.php
- plugins/webkul/employees/src/Models/Department.php
> Issue #661 has been fixed.

- plugins/webkul/employees/src/Filament/Clusters/Configurations/Resources/JobPositionResource.php
> Issue #672 has been fixed.

- plugins/webkul/employees/resources/lang/en/filament/resources/employee.php
- plugins/webkul/employees/src/Filament/Resources/EmployeeResource.php
> Issue #622 has been fixed.

- plugins/webkul/security/src/Filament/Resources/RoleResource.php
- plugins/webkul/security/src/Filament/Resources/RoleResource/Pages/CreateRole.php
- plugins/webkul/security/src/Filament/Resources/RoleResource/Pages/EditRole.php
Issue #696 and #695 has been fixed.
> Issue #696 and #695 has been fixed.

- plugins/webkul/projects/src/Filament/Widgets/TopAssigneesWidget.php
- plugins/webkul/projects/src/Filament/Widgets/TopProjectsWidget.php
> Issue #688 has been fixed.

- plugins/webkul/blogs/database/migrations/2025_09_03_070414_alter_blogs_posts_table.php
- plugins/webkul/blogs/resources/lang/en/filament/admin/clusters/configurations/resources/category.php
- plugins/webkul/blogs/resources/views/filament/customer/resources/post/pages/list-records.blade.php
- plugins/webkul/blogs/src/BlogServiceProvider.php
- plugins/webkul/blogs/src/Filament/Admin/Clusters/Configurations/Resources/CategoryResource.php
- plugins/webkul/blogs/src/Filament/Admin/Resources/PostResource.php
- plugins/webkul/security/src/Models/User.php
- plugins/webkul/website/resources/views/filament/customer/header/auth-links.blade.php
Fixed Issue #512 and Issue #513
> Issue #512

- plugins/webkul/blogs/database/migrations/2025_09_03_070414_alter_blogs_posts_table.php
fixed blogs plugin installation issue
> fixed blogs plugin installation issue

- plugins/webkul/support/resources/lang/en/filament/pages/profile.php
- plugins/webkul/support/src/Filament/Pages/Profile.php
- routes/web.php
> Issue #755 has been fixed.

- plugins/webkul/sales/resources/lang/en/filament/clusters/orders/resources/quotation/actions/send-by-email.php
- plugins/webkul/sales/src/Filament/Clusters/Orders/Resources/QuotationResource/Actions/SendByEmailAction.php
- plugins/webkul/sales/src/SaleManager.php
Removed notification from SendByEmailAction and moved it to SaleManager::sendByEmail method to handle double notification
> fix double notification on Quotation mailing

- plugins/webkul/invoices/src/Filament/Clusters/Vendors/Resources/ProductResource.php
- plugins/webkul/sales/src/Filament/Clusters/Orders/Resources/QuotationResource/Actions/CreateInvoiceAction.php
- plugins/webkul/sales/src/Filament/Clusters/Orders/Resources/QuotationResource/Pages/ManageInvoices.php
- plugins/webkul/sales/src/SaleManager.php
- plugins/webkul/sales/src/Settings/InvoiceSettings.php
> sale Invoice Creation Issue

- .github/ISSUE_TEMPLATE/bug.yml
> fixed unique name issue
